# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

y = torch.rand(7,7)
y
# Create random tensor


tensor([[0.2693, 0.2819, 0.8156, 0.6158, 0.3519, 0.7113, 0.4883],
        [0.2650, 0.6504, 0.2285, 0.2750, 0.9928, 0.4960, 0.7637],
        [0.4626, 0.3957, 0.2644, 0.2627, 0.0369, 0.7389, 0.2982],
        [0.3066, 0.6256, 0.8559, 0.0807, 0.8173, 0.6537, 0.2397],
        [0.1217, 0.7308, 0.6628, 0.7085, 0.7146, 0.8069, 0.7614],
        [0.6969, 0.2191, 0.2071, 0.2722, 0.7737, 0.2350, 0.0013],
        [0.8877, 0.3023, 0.6083, 0.2782, 0.8011, 0.9435, 0.1960]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [6]:
# Create another random tensor
x = torch.rand(1,7)
# Perform matrix multiplication
z = torch.matmul(y,x.T)
z

tensor([[1.1683],
        [1.2338],
        [0.8139],
        [1.3168],
        [1.3930],
        [1.0010],
        [1.4979]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [9]:
# Set manual seed
import random

torch.manual_seed(0)

# Create two random tensors
y = torch.rand(7,7)
x = torch.rand(1,7)

# Matrix multiply tensors
z = torch.matmul(y, x.T)
z, z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [10]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [12]:
# Set random seed
torch.manual_seed(1234)
a = torch.rand(2,3)
b = torch.rand(2,3)
# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")
# Create two random tensors on GPU
a_on_gpu = a.to(device)
b_on_gpu = b.to(device)
print(a_on_gpu, "\n", b_on_gpu)

Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') 
 tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [15]:
# Perform matmul on tensor_A and tensor_B
c_on_gpu = torch.matmul(a_on_gpu, b_on_gpu.T)
print(c_on_gpu, c_on_gpu.shape)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [16]:
# Find max
max = torch.max(c_on_gpu)
# Find min
min = torch.min(c_on_gpu)

print(max, min)

tensor(0.5617, device='cuda:0') tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [17]:
# Find arg max
argmax = torch.argmax(c_on_gpu)

# Find arg min
argmin = torch.argmin(c_on_gpu)

print(argmax, argmin)

tensor(3, device='cuda:0') tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [19]:
# Set seed
torch.manual_seed(7)

# Create random tensor
r = torch.rand(1,1,1,10)

# Remove single dimensions
r_sqz = torch.squeeze(r)

# Print out tensors and their shapes
print(r, "\n", r_sqz)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) 
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
